# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 5 # pagination based on number of posts
paginate_path: "blog/posts/:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Rodrigo Araújo

description: Stylish Jekyll Theme
author:
  name: Rodrigo Araújo
  email: rod.dearaujo@gmail.com
  github: digorithm
  twitter: digorithm
  bio: "Stories, Thoughts and Ideas on Computer Science, Mathematics and Technology"

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
