#
###################################
# Site wide configuration
####################################
#
title: Rodrigo Araujo
email: rod.dearaujo@gmail.com
description: Thoughts and stories on computer science, software engineering and mathematics
url: # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
gems: [jekyll-paginate]
paginate: 3
paginate_path: "page:num"
timezone:          Vancouver/Canada
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

gems: [jekyll-paginate]
pages_list:
  Home: '/'
  Blog: '/blog'
  Categories: '/categories'
  Projects: '/projects'
  Publications: '/publications'
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Rodrigo Araujo
  avatar: leonids-logo.png
  job: "Computer scientist and SW Engineer"
  bio: "Thoughts and stories on computer science, software engineering and mathematics"
  email: rod.dearaujo@gmail.com
  disqus-shortname:
  twitter: digorithm
  facebook: #username
  google:
    plus: #username
    analytics: UA-38327934-3
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: digorithm
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
